[custom]
;不要随意改变关键字，否则会导致出错

;移除关键词
exclude_remarks=(Data Left|Remain:|Traffic:|Expir[ey]|Reset|剩[余餘]流量|流量：|[到过過效]期|[时時][间間]|重置|分割线|残り使用容量|有効期限|リセット|海外|官网|过期|剩余|群组|虚拟|虚通|购买|倒卖|接入|到期|备用|客服|禁止|generation)

;设置规则标志位  顺序匹配

;华为 160
ruleset=🇨🇳华为,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Huawei/Huawei.list

;IPTV  1
ruleset=📺IPTV,https://raw.githubusercontent.com/wyychelsea/rules/refs/heads/main/IPTV.list
;谷歌搜索  1
ruleset=🔍谷歌搜索,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleSearch/GoogleSearch.list
;Chromecast  1
ruleset=📺Chromecast,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Chromecast/Chromecast.list
;GoogleVoice  1
ruleset=💬GoogleVoice,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleVoice/GoogleVoice.list
;哔哩哔哩  2
ruleset=📺哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.list
;PLEX  2
ruleset=📺PLEX,https://raw.githubusercontent.com/wyychelsea/rules/refs/heads/main/PLEX.list
;多邻国  2
ruleset=🐤多邻国,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Duolingo/Duolingo.list
;尼日利亚网站  2
;ruleset=🇳🇬尼日利亚网站,https://raw.githubusercontent.com/wyychelsea/rules/refs/heads/main/NG_websites.list
;喷泉  3
ruleset=⛲喷泉,https://raw.githubusercontent.com/wyychelsea/rules/refs/heads/main/Fountain.list
;TIDAL  4
ruleset=🎵TIDAL,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TIDAL/TIDAL.list
;土耳其网站  4
ruleset=🇹🇷土耳其网站,https://raw.githubusercontent.com/wyychelsea/rules/refs/heads/main/TR_websites.list
;4
ruleset=🟢直连,https://raw.githubusercontent.com/wyychelsea/rules/refs/heads/main/Direct.list
;测速  5
ruleset=🚀Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
;机场  6
ruleset=🛩机场,https://raw.githubusercontent.com/wyychelsea/rules/refs/heads/main/Airport.list
;巴哈姆特  7
ruleset=📺巴哈姆特,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
;AppleTV  8
ruleset=🍎AppleTV,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.list
;微软Bing  9
ruleset=Ⓜ️微软Bing,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Bing/Bing.list
;远程连接  9
ruleset=🖥️远程连接,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/RemoteDesktop/RemoteDesktop.list
;Binance  12
ruleset=💰Binance,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance.list
;抖音  13
ruleset=🎵抖音,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/DouYin/DouYin.list
;17
ruleset=🟢直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list
;WhatsApp  17
ruleset=💬WhatsApp,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list
;OneDrive  18
ruleset=Ⓜ️OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list
;群晖  19
ruleset=🗄群晖,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Synology/Synology.list
;Twitch  22
ruleset=🐭Twitch,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitch/Twitch.list
;Spotify  30
ruleset=🎵Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
;WeChat  31
ruleset=💬WeChat,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.list
;GitHub  31
ruleset=💻GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
;Qobuz  33
ruleset=🎵Qobuz,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Qobuz/Qobuz.list
;34
ruleset=🟢直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.list
;OpenAI  35
ruleset=🤖OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
;谷歌FCM  41
ruleset=📢谷歌FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list
;eBay  44
ruleset=🛒eBay,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/eBay/eBay.list
;Telegram  46
ruleset=💬Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
;HBO  48
ruleset=🎦HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.list
;Bestbuy  82
ruleset=🛒Bestbuy,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bestbuy/Bestbuy.list
;Nintendo  127
ruleset=🎮任天堂,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Nintendo/Nintendo.list
;哔哩哔哩  129
ruleset=📺哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
;141
ruleset=🟢直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list

;Disney  174
ruleset=🐹Disney+,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
;YouTube  183
ruleset=📹YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
;Amazon  203
ruleset=🛒Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Amazon/Amazon.list
;PayPal  247
ruleset=💰PayPal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list
;国内媒体  411
ruleset=🌏国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMedia/ChinaMedia.list

;游戏
;Epic  15
;ruleset=🎮游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Epic/Epic.list
;Origin  7
;ruleset=🎮游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Origin/Origin.list
;Sony  116
;ruleset=🎮游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Sony/Sony.list
;Steam  54
ruleset=🎮Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Steam/Steam.list
;全部游戏  597
;ruleset=🎮游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Game/Game.list

;微软服务  670
ruleset=Ⓜ️微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
;谷歌  708
ruleset=🔴🟡🔵🟢谷歌,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
;Netflix  1157
ruleset=🎥Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
;苹果服务  1589
ruleset=🍎苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
;国外媒体  2265
ruleset=🌍国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia.list

;即时通讯
;购物
;流媒体

;3728
ruleset=🟢直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
;必须沉底  976
ruleset=🚀节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ProxyLite/ProxyLite.list
ruleset=🟢直连,[]GEOIP,CN
ruleset=🐟漏网之鱼,[]FINAL
;设置规则标志位

;分组开始
custom_proxy_group=🚀节点选择`select`[]🔯故障转移`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]🏠家宽`[]💸高倍`[]🇦🇷阿根廷`[]🇮🇳印度`[]🇹🇷土耳其`[]🇳🇬尼日利亚`[]🇱🇰斯里兰卡`[]🇪🇬埃及`[]📌手动`[]🟢直连
custom_proxy_group=🎵Spotify`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]🇦🇷阿根廷`[]🇮🇳印度`[]🇹🇷土耳其`[]🇳🇬尼日利亚`[]🇵🇭菲律宾`[]🇱🇰斯里兰卡`[]🇪🇬埃及`[]📌手动
custom_proxy_group=📹YouTube`select`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]🇦🇷阿根廷`[]🇮🇳印度`[]🇹🇷土耳其`[]🇳🇬尼日利亚`[]🇵🇭菲律宾`[]🇱🇰斯里兰卡`[]🇪🇬埃及`[]📌手动
custom_proxy_group=🐭Twitch`select`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🎥流媒体节点`select`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]🇦🇷阿根廷`[]🇮🇳印度`[]🇹🇷土耳其`[]🇳🇬尼日利亚`[]🇱🇰斯里兰卡`[]🇪🇬埃及`[]📌手动`[]🟢直连
custom_proxy_group=🔴🟡🔵🟢谷歌`select`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=📌手动`select`(?=.*)^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$
custom_proxy_group=🛩机场`select`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG
custom_proxy_group=🔍谷歌搜索`select`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🤖OpenAI`select`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=💻GitHub`select`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=📺Chromecast`select`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=📢谷歌FCM`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=💬GoogleVoice`select`[]🇺🇸美国其他`[]🇺🇸美国TAG`[]🚀节点选择`[]🏡自建`[]📌手动
custom_proxy_group=💬Telegram`select`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=💬WhatsApp`select`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🎵TIDAL`select`[]🇦🇷阿根廷`[]🚀节点选择`[]🇺🇸美国其他`[]🇺🇸美国TAG`[]🟢直连
custom_proxy_group=🎵Qobuz`select`[]🇦🇷阿根廷`[]🚀节点选择`[]🇺🇸美国其他`[]🇺🇸美国TAG`[]🟢直连
custom_proxy_group=🎥Netflix`select`[]🎥Netflix节点`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🐹Disney+`select`[]🎥Netflix节点`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🍎AppleTV`select`[]🎥Netflix节点`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🎦HBO`select`[]🎥Netflix节点`[]🚀节点选择`[]🎥流媒体节点`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]🇦🇷阿根廷`[]📌手动
custom_proxy_group=📺巴哈姆特`select`[]🇨🇳台湾其他`[]🇨🇳台湾TAG
custom_proxy_group=📺哔哩哔哩`select`[]🟢直连`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG
custom_proxy_group=🐤多邻国`select`[]🚀节点选择`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇪🇬埃及`[]🟢直连
custom_proxy_group=🇹🇷土耳其网站`select`[]🇹🇷土耳其`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🛒Amazon`select`[]🇺🇸美国其他`[]🇺🇸美国TAG`[]🇮🇳印度`[]🚀节点选择
custom_proxy_group=🛒Bestbuy`select`[]🇺🇸美国其他`[]🇺🇸美国TAG`[]🚀节点选择
custom_proxy_group=🛒eBay`select`[]🇺🇸美国其他`[]🇺🇸美国TAG`[]🚀节点选择
custom_proxy_group=💰PayPal`select`[]🟢直连
custom_proxy_group=💰Binance`select`[]🇯🇵日本其他`[]🇯🇵日本TAG`[]🚀节点选择
custom_proxy_group=🚀Speedtest`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=💬WeChat`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=📺IPTV`select`[]🟢直连
custom_proxy_group=🗄群晖`select`[]🟢直连`[]🚀节点选择
custom_proxy_group=📺PLEX`select`[]🟢直连
custom_proxy_group=🖥️远程连接`select`[]🟢直连
custom_proxy_group=⛲喷泉`select`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🌍国外媒体`select`[]🚀节点选择`[]🟢直连`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🌏国内媒体`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=Ⓜ️微软Bing`select`[]🚀节点选择`[]🟢直连`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=Ⓜ️OneDrive`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=Ⓜ️微软服务`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🍎苹果服务`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🎮任天堂`select`[]🟢直连`[]🚀节点选择`[]🏡自建`[]🏠家宽`[]🇯🇵日本其他`[]🇯🇵日本TAG`[]💸高倍`[]📌手动
custom_proxy_group=🎮Steam`select`[]🚀节点选择`[]🟢直连`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动
custom_proxy_group=🎵抖音`select`[]🟢直连
custom_proxy_group=🇨🇳华为`select`[]🟢直连
custom_proxy_group=🟢直连`select`[]DIRECT
custom_proxy_group=🐟漏网之鱼`select`[]🚀节点选择`[]🟢直连`[]🏡自建`[]🇨🇳台湾其他`[]🇭🇰香港其他`[]🇺🇸美国其他`[]🇸🇬狮城其他`[]🇯🇵日本其他`[]🇨🇳台湾TAG`[]🇭🇰香港TAG`[]🇺🇸美国TAG`[]🇸🇬狮城TAG`[]🇯🇵日本TAG`[]📌手动

custom_proxy_group=🏠家宽`select`(家宽|家庭|住宅|游戏|星链|蜂窝)
custom_proxy_group=💸高倍`select`(?=.*(倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x))^((?!(家宽|家庭|游戏|星链|蜂窝)).)*$
custom_proxy_group=🎥Netflix节点`select`(奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=🏡自建`select`(自建)
;custom_proxy_group=♻️自动`url-test`(?=.*)^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🔯故障转移`fallback`(?=.*(自建|TW|Taiwan|台湾|台北|台中|新北|彰化|CHT|HINET|台|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|America))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇨🇳台湾其他`url-test`!!GROUPID=!1!!(?=.*(TW|Taiwan|台湾|台北|台中|新北|彰化|CHT|HINET|台))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇨🇳台湾TAG`url-test`!!GROUPID=1!!(?=.*(TW|Taiwan|台湾|台北|台中|新北|彰化|CHT|HINET|台))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
;custom_proxy_group=🇨🇳台湾`url-test`(?=.*(TW|Taiwan|台湾|台北|台中|新北|彰化|CHT|HINET|台))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇭🇰香港其他`url-test`!!GROUPID=!1!!(?=.*(HK|Hong.*?Kong|香港|港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|京港))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇭🇰香港TAG`url-test`!!GROUPID=1!!(?=.*(HK|Hong.*?Kong|香港|港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|京港))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
;custom_proxy_group=🇭🇰香港`url-test`(?=.*(HK|Hong.*?Kong|香港|港|深港|沪港|呼港|HKT|HKBN|HGC|WTT|CMI|京港))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇺🇸美国其他`url-test`!!GROUPID=!1!!(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|America))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇺🇸美国TAG`url-test`!!GROUPID=1!!(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|America))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
;custom_proxy_group=🇺🇸美国`url-test`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|America))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇸🇬狮城其他`url-test`!!GROUPID=!1!!(?=.*(新加坡|新|坡|狮城|SG|Singapore))^((?!(新奥尔良|家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇸🇬狮城TAG`url-test`!!GROUPID=1!!(?=.*(新加坡|新|坡|狮城|SG|Singapore))^((?!(新奥尔良|家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇯🇵日本其他`url-test`!!GROUPID=!1!!(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan))^((?!(家宽|家庭|游戏|星链|蜂窝|尼日|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇯🇵日本TAG`url-test`!!GROUPID=1!!(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan))^((?!(家宽|家庭|游戏|星链|蜂窝|尼日|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
;custom_proxy_group=🇰🇷韩国`url-test`(?=.*(KR|Korea|KOR|首尔|韩|韓))^((?!(家宽|家庭|游戏|星链|蜂窝|倍|2.0|2x|3.0|3x|4.0|4x|5.0|5x|10.0|10x|20.0|20x)).)*$`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇮🇳印度`url-test`(IN|India|IND|印度|度)`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇪🇬埃及`url-test`(EG|Egypt|EGY|埃及)`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇵🇭菲律宾`url-test`(PH|Philippines|PHL|菲律宾|菲)`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇹🇷土耳其`url-test`(TR|Turkey|TUR|土耳其)`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇦🇷阿根廷`url-test`(AR|Argentina|ARG|阿根廷)`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇱🇰斯里兰卡`url-test`(LK|Sri Lanka|LKA|斯里兰卡)`https://www.apple.com/library/test/success.html`300,,50
custom_proxy_group=🇳🇬尼日利亚`url-test`(NG|Nigeria|NGA|尼日利亚)`https://www.apple.com/library/test/success.html`300,,50
;custom_proxy_group=🇵🇰巴基斯坦`url-test`(PK|Pakistan|PAK|巴基斯坦)`https://www.apple.com/library/test/success.html`300,,50
;分组结束

;覆盖原始规则
enable_rule_generator=true
overwrite_original_rules=true

;NF|奈飞|解锁|Netflix|NETFLIX|Media|
